/*
This file is part of Giswater 3
The program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This version of Giswater is provided by Giswater Association
*/
INSERT INTO sys_fprocess (fid, fprocess_name, project_type, parameters, "source", isaudit, fprocess_type, addparam, except_level, except_msg, except_msg_feature, query_text, info_msg, function_name) VALUES(524, 'Null values on valve_type of virtualvalve', 'ws', NULL, 'core', true, 'Check epa-data', NULL, 1, 'virtualvalves with null values on valv_type column.', NULL, 'SELECT n.node_id, n.nodecat_id, n.the_geom, expl_id FROM man_valve JOIN v_prefix_node n USING (node_id) 
WHERE n.state = 1 AND (broken IS NULL OR closed IS NULL)', 'Virtualvalve valv_type checked. No mandatory values missed.', '[gw_fct_pg2epa_check_data]');

INSERT INTO sys_fprocess (fid, fprocess_name, project_type, parameters, "source", isaudit, fprocess_type, addparam, except_level, except_msg, except_msg_feature, query_text, info_msg, function_name) VALUES(525, 'Null values on valve status of virtualvalves', 'ws', NULL, 'core', true, 'Check epa-data', NULL, 3, 'virtualvalves with null values on mandatory column status.', NULL, 'SELECT * FROM v_edit_inp_virtualvalve WHERE status IS NULL AND state > 0', 'Virtualvalve status checked. No mandatory values missed.', '[gw_fct_pg2epa_check_data]');

INSERT INTO sys_fprocess (fid, fprocess_name, project_type, parameters, "source", isaudit, fprocess_type, addparam, except_level, except_msg, except_msg_feature, query_text, info_msg, function_name) VALUES(526, 'Null values on virtualvalve pressure', 'ws', NULL, 'core', true, 'Check epa-data', NULL, 3, 'PBV-PRV-PSV virtualvalves with null values on the mandatory column for Pressure valves.', NULL, 'SELECT * FROM v_edit_inp_virtualvalve WHERE ((valv_type=''PBV'' OR valv_type=''PRV'' OR valv_type=''PSV'') AND (pressure IS NULL))', 'PBC-PRV-PSV virtualvalves checked. No mandatory values missed.', '[gw_fct_pg2epa_check_data]');

INSERT INTO sys_fprocess (fid, fprocess_name, project_type, parameters, "source", isaudit, fprocess_type, addparam, except_level, except_msg, except_msg_feature, query_text, info_msg, function_name) VALUES(527, 'Null values on GPV virtualvalve config', 'ws', NULL, 'core', true, 'Check epa-data', NULL, 3, 'GPV virtualvalves with null values on mandatory column for General purpose valves.', NULL, 'SELECT * FROM v_edit_inp_virtualvalve WHERE ((valv_type=''GPV'') AND (curve_id IS NULL))', 'GPV virtualvalves checked. No mandatory values missed.', '[gw_fct_pg2epa_check_data]');

INSERT INTO sys_fprocess (fid, fprocess_name, project_type, parameters, "source", isaudit, fprocess_type, addparam, except_level, except_msg, except_msg_feature, query_text, info_msg, function_name) VALUES(528, 'Null values on TCV virtualvalve config', 'ws', NULL, 'core', true, 'Check epa-data', NULL, 3, 'TCV virtualvalves with null values on mandatory column for Losses Valves.', NULL, 'SELECT * FROM v_edit_inp_virtualvalve WHERE valv_type=''TCV'' AND coef_loss IS NULL', 'TCV virtualvalves checked. No mandatory values missed.', '[gw_fct_pg2epa_check_data]');

INSERT INTO sys_fprocess (fid, fprocess_name, project_type, parameters, "source", isaudit, fprocess_type, addparam, except_level, except_msg, except_msg_feature, query_text, info_msg, function_name) VALUES(529, 'Null values on FCV virtualvalve config', 'ws', NULL, 'core', true, 'Check epa-data', NULL, 3, 'FCV virtualvalves with null values on mandatory column for Flow Control Valves.', NULL, 'SELECT * FROM v_edit_inp_virtualvalve WHERE ((valv_type=''FCV'') AND (flow IS NULL))', 'FCV virtualvalves checked. No mandatory values missed.', '[gw_fct_pg2epa_check_data]');
INSERT INTO sys_fprocess (fid, fprocess_name, project_type, parameters, "source", isaudit, fprocess_type, addparam, except_level, except_msg, except_msg_feature, query_text, info_msg, function_name) VALUES(530, 'Null values on virtualpumps type', 'ws', NULL, 'core', true, 'Check epa-data', NULL, 3, 'virtualpumps with null values on pump_type column. virtualpump''''s with null values on pump_type column.', NULL, 'SELECT * FROM v_edit_inp_virtualpump WHERE pump_type IS NULL', 'Virtualpumps checked. No mandatory values for pump_type missed. Virtualpumps checked. No mandatory values for pump_type missed.', '[gw_fct_plan_check_data, gw_fct_pg2epa_check_data]');

INSERT INTO sys_fprocess (fid, fprocess_name, project_type, parameters, "source", isaudit, fprocess_type, addparam, except_level, except_msg, except_msg_feature, query_text, info_msg, function_name) VALUES(531, 'Null values on virtualpump curve_id ', 'ws', NULL, 'core', true, 'Check epa-data', NULL, 3, 'virtualpumps with null values at least on mandatory column curve_id. virtualpumps with null values at least on mandatory column curve_id.', NULL, 'SELECT * FROM v_edit_inp_virtualpump WHERE curve_id IS NULL', 'Virtualpumps checked. No mandatory values for curve_id missed. Virtualpumps checked. No mandatory values for curve_id missed.', '[gw_fct_plan_check_data, gw_fct_pg2epa_check_data]');

INSERT INTO sys_fprocess (fid, fprocess_name, project_type, parameters, "source", isaudit, fprocess_type, addparam, except_level, except_msg, except_msg_feature, query_text, info_msg, function_name) VALUES(534, 'Check if defined nodes (nodeParent) exist in a database', 'ws', NULL, 'core', true, 'Check graph-data', NULL, 2, 'nodes that are configured as nodeParent for v_prefix_v_graphclass but is not operative on node table.', NULL, 'SELECT b.node_id, b.v_graphclass_id as zone_id FROM (
SELECT v_graphclass_id, graphconfig::json->''use''->0->>''nodeParent'' as node_id FROM v_prefix_v_graphclass)b 
WHERE node_id::text not in (select node_id FROM node WHERE state=1)', 'All nodes defined as nodeParent on v_prefix_v_graphclass exists on DB.', '[gw_fct_graphanalytics_check_data]');

INSERT INTO sys_fprocess (fid, fprocess_name, project_type, parameters, "source", isaudit, fprocess_type, addparam, except_level, except_msg, except_msg_feature, query_text, info_msg, function_name) VALUES(535, 'State not according with state_type', 'ws', NULL, 'core', true, 'Check om-data', NULL, 3, 'features with state without concordance with state_type. Please, check your data before continue features with state without concordance with state_type. Please, check your data before continue', NULL, 'SELECT arc_id as id, a.state, state_type FROM v_edit_arc a JOIN value_state_type b ON id=state_type WHERE a.state <> b.state UNION 
SELECT node_id as id, a.state, state_type FROM v_edit_node a JOIN value_state_type b ON id=state_type WHERE a.state <> b.state UNION 
SELECT connec_id as id, a.state, state_type FROM v_edit_connec a JOIN value_state_type b ON id=state_type WHERE a.state <> b.state UNION 
SELECT element_id as id, a.state, state_type FROM v_edit_element a JOIN value_state_type b ON id=state_type WHERE a.state <> b.state', 'No features without concordance against state and state_type.   No features without concordance against state and state_type.', '[gw_fct_om_check_data]');


UPDATE sys_fprocess SET fprocess_name='OM check data', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=125;
UPDATE sys_fprocess SET fprocess_name='Mincutzones identification', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=129;
UPDATE sys_fprocess SET fprocess_name='Inlet Sectorization', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=130;
UPDATE sys_fprocess SET fprocess_name='Mincut conflict scenario result', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=131;
UPDATE sys_fprocess SET fprocess_name='Dynamic minimun sector analysis', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=134;
UPDATE sys_fprocess SET fprocess_name='Epa inlet flowtrace', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-network', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=139;
UPDATE sys_fprocess SET fprocess_name='Check dint value for cat_node acting as [SHORTPIPE or VALVE or PUMP]', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-config', addparam=NULL, except_level=2, except_msg='registers on node''s catalog acting as [SHORTPIPE or VALVE] with dint not defined.''', except_msg_feature=NULL, query_text='SELECT * FROM cat_node WHERE dint IS NULL AND id IN 
(SELECT DISTINCT(nodecat_id) from v_edit_node WHERE epa_type IN (''SHORTPIPE'', ''VALVE''))', info_msg='Dint for node''''s catalog checked. No values missed for SHORTPIPES OR VALVES', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=142;
UPDATE sys_fprocess SET fprocess_name='District Quality Areas', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=144;
UPDATE sys_fprocess SET fprocess_name='District Metering Areas', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=145;
UPDATE sys_fprocess SET fprocess_name='Pressure Zonification', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=146;
UPDATE sys_fprocess SET fprocess_name='Static pressure value', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=147;
UPDATE sys_fprocess SET fprocess_name='Pipe leak probability', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=148;
UPDATE sys_fprocess SET fprocess_name='EPA vnodes trim arcs', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=150;
UPDATE sys_fprocess SET fprocess_name='Inlets with null mandatory values', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=2, except_msg='inlets with null values at least on mandatory columns for inlets (initlevel, minlevel, maxlevel, diameter, minvol).Take a look on temporal table to details.', except_msg_feature=NULL, query_text='SELECT * FROM temp_anl_node WHERE fid=153 AND cur_user=current_user', info_msg='Inlets checked. No mandatory values missed.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=153;
UPDATE sys_fprocess SET fprocess_name='Nodes single capacity', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=155;
UPDATE sys_fprocess SET fprocess_name='Nodes double capacity', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=156;
UPDATE sys_fprocess SET fprocess_name='Nodes single capacity but not double', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=157;
UPDATE sys_fprocess SET fprocess_name='Nodes coupled capacity', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=158;
UPDATE sys_fprocess SET fprocess_name='EPA check vnodes over nod2arc', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-network', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=159;
UPDATE sys_fprocess SET fprocess_name='EPA connecs with no hydrometer', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=160;
UPDATE sys_fprocess SET fprocess_name='Check if pattern method is compatible with networkmode', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=161;
UPDATE sys_fprocess SET fprocess_name='Ckeck if pattern for connec is the same for all connecs related to the same vnode', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=162;
UPDATE sys_fprocess SET fprocess_name='Nodes without elevation', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=2, except_msg='nodes without elevation. Take a look on temporal table for details.', except_msg_feature=NULL, query_text='SELECT * FROM v_edit_node JOIN selector_sector USING (sector_id) WHERE elevation IS NULL AND cur_user = current_user', info_msg='No nodes with null values on field elevation have been found.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=164;
UPDATE sys_fprocess SET fprocess_name='Nodes with elevation=0', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=2, except_msg='nodes with elevation=0.', except_msg_feature=NULL, query_text='SELECT * FROM v_edit_node JOIN selector_sector USING (sector_id) WHERE elevation = 0 AND cur_user = current_user', info_msg='No nodes with ''''0'''' on field elevation have been found.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=165;
UPDATE sys_fprocess SET fprocess_name='Node2arc with more than two arcs', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-topology', addparam=NULL, except_level=2, except_msg='node2arcs with more than two arcs. It''''s impossible to continue''', except_msg_feature=NULL, query_text='SELECT * FROM (
SELECT node_id, nodecat_id, node.the_geom, node.expl_id FROM node  JOIN selector_sector USING (sector_id) 
JOIN v_edit_arc a1 ON node_id=a1.node_1  AND node.epa_type IN (''SHORTPIPE'', ''VALVE'', ''PUMP'') WHERE current_user=cur_user 
UNION ALL SELECT node_id, nodecat_id, node.the_geom, node.expl_id FROM node  JOIN selector_sector USING (sector_id) 
JOIN v_edit_arc a1 ON node_id=a1.node_2  AND node.epa_type IN (''SHORTPIPE'', ''VALVE'', ''PUMP'') WHERE current_user=cur_user)a 
GROUP by node_id, nodecat_id, the_geom, expl_id HAVING count(*) > 2', info_msg='No results found looking for node2arcs with more than two arcs.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=166;
UPDATE sys_fprocess SET fprocess_name='Node2arc with less than two arcs', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-topology', addparam=NULL, except_level=2, except_msg='mandatory node2arcs with less than two arcs.''', except_msg_feature=NULL, query_text='SELECT *FROM (
SELECT node_id, nodecat_id, v_edit_node.the_geom, v_edit_node.expl_id FROM v_edit_node 
JOIN selector_sector USING (sector_id)   JOIN v_edit_arc a1 ON node_id=a1.node_1 WHERE cur_user = current_user 
AND v_edit_node.epa_type IN (''VALVE'', ''PUMP'') AND a1.sector_id IN (SELECT sector_id FROM selector_sector WHERE cur_user=current_user) UNION ALL
SELECT node_id, nodecat_id, v_edit_node.the_geom, v_edit_node.expl_id FROM v_edit_node  JOIN selector_sector USING (sector_id) 
JOIN v_edit_arc a1 ON node_id=a1.node_1 WHERE cur_user = current_user  AND v_edit_node.epa_type IN (''VALVE'', ''PUMP'') 
AND a1.sector_id IN (SELECT sector_id FROM selector_sector WHERE cur_user=current_user))a 
GROUP by node_id, nodecat_id, the_geom, expl_id HAVING count(*) < 2', info_msg='No results found for mandatory node2arcs with less than two arcs.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=167;
UPDATE sys_fprocess SET fprocess_name='Check pipes with status CV', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=2, except_msg='CV pipes. Be carefull with the sense of pipe and check that node_1 and node_2 are on the right direction to prevent reverse flow.', except_msg_feature=NULL, query_text='SELECT * FROM temp_anl_arc WHERE fid = 169 AND cur_user=current_user', info_msg='No results found for CV pipes', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=169;
UPDATE sys_fprocess SET fprocess_name='Check concordance of to_arc valves', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=2, except_msg='valves with wrong to_arc value according to the current closest arcs.', except_msg_feature=NULL, query_text='SELECT * FROM temp_anl_node WHERE fid = 170 AND cur_user=current_user', info_msg='Valve to_arc wrong values checked. No inconsistencies have been detected according to the current closest arcs.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=170;
UPDATE sys_fprocess SET fprocess_name='Check concordance of to_arc pumps', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=3, except_msg='pumps with wrong to_arc value according to the current closest arcs.', except_msg_feature=NULL, query_text='SELECT * FROM temp_anl_node WHERE fid = 171 AND cur_user=current_user', info_msg='Pump to_arc wrong values checked. No inconsistencies have been detected according with the current closest arcs.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=171;
UPDATE sys_fprocess SET fprocess_name='Pump curve with 3 points', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-result', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=172;
UPDATE sys_fprocess SET fprocess_name='go2crm connec dma values', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=173;
UPDATE sys_fprocess SET fprocess_name='crm2pg connec_x_data flow values', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=174;
UPDATE sys_fprocess SET fprocess_name='Null values on closed/broken values for valves', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check graph-data', addparam=NULL, except_level=3, except_msg='valves (state=1) with broken or closed with NULL values.', except_msg_feature=NULL, query_text='SELECT n.node_id, n.nodecat_id, n.the_geom, expl_id FROM man_valve JOIN v_prefix_node n USING (node_id) 
WHERE n.state = 1 AND (broken IS NULL OR closed IS NULL)', info_msg='There are not operative valves with null values on closed/broken fields.', function_name='[gw_fct_graphanalytics_check_data, gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=176;
UPDATE sys_fprocess SET fprocess_name='inlet_x_exploitation with null/wrong values', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check graph-data', addparam=NULL, except_level=3, except_msg='rows with exploitation bad configured on the config_graph_mincut table. Please check your data before continue.', except_msg_feature=NULL, query_text='SELECT * FROM config_graph_mincut cgi INNER JOIN node n ON cgi.node_id = n.node_id  WHERE n.expl_id NOT IN 
(SELECT expl_id FROM exploitation WHERE active IS TRUE)', info_msg='It seems config_graph_mincut table is well configured. At least, table is filled with nodes from all exploitations. All tanks are defined in config_graph_mincut.', function_name='[gw_fct_graphanalytics_check_data, gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=177;
UPDATE sys_fprocess SET fprocess_name='node_type filled with gradelimiter values', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check graph-config', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=178;
UPDATE sys_fprocess SET fprocess_name='dma-nodeparent acording with graphdelimiter', project_type='ws', parameters='{"graphClass":"DMA"}'::json, "source"='core', isaudit=true, fprocess_type='Check graph-config', addparam=NULL, except_level=2, except_msg='nodes with cat_feature_node.graph_delimiter=''DMA'' not configured on the dma table. nodes with cat_feature_node.graph_delimiter=''DMA'' configured for unactive mapzone.', except_msg_feature=NULL, query_text='SELECT node_id, nodecat_id, the_geom, a.active, v_prefix_node.expl_id FROM v_prefix_node JOIN cat_node c ON id=nodecat_id JOIN cat_feature_node n ON n.id=c.nodetype_id LEFT JOIN (SELECT node_id, active FROM v_prefix_node JOIN (SELECT (json_array_elements_text((graphconfig::json->>''use'')::json))::json->>''nodeParent'' as node_id,   active FROM v_prefix_dma WHERE graphconfig IS NOT NULL )a USING (node_id)) a USING (node_id) WHERE graph_delimiter=''DMA'' AND (a.node_id IS NULL  OR node_id NOT IN (SELECT (json_array_elements_text((graphconfig::json->>''ignore'')::json))::text FROM v_prefix_dma WHERE active IS TRUE))  AND v_prefix_node.state > 0', info_msg='All nodes with cat_feature_node.graphdelimiter=''DMA'' are defined as nodeParent on dma.graphconfig', function_name='[gw_fct_graphanalytics_check_data, gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=180;
UPDATE sys_fprocess SET fprocess_name='dqa-nodeparent acording with graphdelimiter', project_type='ws', parameters='{"graphClass":"DQA"}'::json, "source"='core', isaudit=true, fprocess_type='Check graph-data', addparam=NULL, except_level=2, except_msg='nodes with cat_feature_node.graph_delimiter=''DQA'' not configured on the dqa table. nodes with cat_feature_node.graph_delimiter=''DQA'' configured for unactive mapzone.', except_msg_feature=NULL, query_text='SELECT node_id, nodecat_id, the_geom, a.active,  v_prefix_node.expl_id FROM v_prefix_node JOIN cat_node c ON id=nodecat_id JOIN cat_feature_node n ON n.id=c.nodetype_id  LEFT JOIN (SELECT node_id, active FROM v_prefix_node JOIN (SELECT (json_array_elements_text((graphconfig::json->>''use'')::json))::json->>''nodeParent'' as node_id, active FROM v_prefix_dqa WHERE graphconfig IS NOT NULL )a USING (node_id)) a USING (node_id) WHERE graph_delimiter=''DQA'' AND (a.node_id IS NULL  OR node_id NOT IN (SELECT (json_array_elements_text((graphconfig::json->>''ignore'')::json))::text FROM v_prefix_dqa WHERE active IS TRUE))  AND v_prefix_node.state > 0', info_msg='All nodes with cat_feature_node.graphdelimiter=''DMA'' are defined as nodeParent on dma.graphconfig', function_name='[gw_fct_graphanalytics_check_data, gw_fct_admin_check_data]' WHERE fid=181;
UPDATE sys_fprocess SET fprocess_name='presszone-nodeparent acording with graphdelimiter', project_type='ws', parameters='{"graphClass":"PRESSZONE"}'::json, "source"='core', isaudit=true, fprocess_type='Check graph-data', addparam=NULL, except_level=2, except_msg='nodes with cat_feature_node.graph_delimiter=''PRESSZONE'' not configured on the presszone table. nodes with cat_feature_node.graph_delimiter=''PRESSZONE'' configured for unactive mapzone.', except_msg_feature=NULL, query_text='SELECT node_id, nodecat_id, the_geom, a.active,v_prefix_node.expl_id FROM v_prefix_node JOIN cat_node c ON id=nodecat_id JOIN cat_feature_node n ON n.id=c.nodetype_id  LEFT JOIN (SELECT node_id, active FROM v_prefix_node JOIN (SELECT (json_array_elements_text((graphconfig::json->>''use'')::json))::json->>''nodeParent'' as node_id, active FROM v_prefix_presszone WHERE graphconfig IS NOT NULL )a USING (node_id)) a USING (node_id) WHERE graph_delimiter=''PRESSZONE'' AND (a.node_id IS NULL  OR node_id NOT IN (SELECT (json_array_elements_text((graphconfig::json->>''ignore'')::json))::text FROM v_prefix_presszone WHERE active IS TRUE))  AND v_prefix_node.state > 0', info_msg='All nodes with cat_feature_node.graphdelimiter=''PRESSZONE'' are defined as nodeParent on presszone.graphconfig', function_name='[gw_fct_graphanalytics_check_data, gw_fct_admin_check_data]' WHERE fid=182;
UPDATE sys_fprocess SET fprocess_name='sector-toarc acording with topology', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check graph-config', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=183;
UPDATE sys_fprocess SET fprocess_name='dma-toarc acording with topology', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check graph-config', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=184;
UPDATE sys_fprocess SET fprocess_name='dqa-toarc acording with topology', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check graph-config', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=185;
UPDATE sys_fprocess SET fprocess_name='presszone-toarc acording with topology', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check graph-config', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=186;
UPDATE sys_fprocess SET fprocess_name='Arcs with dma=0', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Not used', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=190;
UPDATE sys_fprocess SET fprocess_name='Nodes with dma=0', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Not used', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=191;
UPDATE sys_fprocess SET fprocess_name='Connecs with dma=0', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Not used', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=192;
UPDATE sys_fprocess SET fprocess_name='Flowtrace disconnected arcs', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=193;
UPDATE sys_fprocess SET fprocess_name='Flowtrace connected arcs', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=194;
UPDATE sys_fprocess SET fprocess_name='Tanks with null mandatory values', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=3, except_msg='tanks with null values at least on mandatory columns for tank (initlevel, minlevel, maxlevel, diameter, minvol).Take a look on temporal table to details', except_msg_feature=NULL, query_text='SELECT * FROM temp_anl_node WHERE fid=198 AND cur_user=current_user', info_msg='Tanks checked. No mandatory values missed.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=198;
UPDATE sys_fprocess SET fprocess_name='Mincut process', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=199;
UPDATE sys_fprocess SET fprocess_name='Set to_arc values for graph delimiters', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check graph-config', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=200;
UPDATE sys_fprocess SET fprocess_name='feature which id is not an integer', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=3, except_msg='which id is not an integer. Please, check your data before continue', except_msg_feature=NULL, query_text='SELECT CASE WHEN arc_id~E''^\\d+$'' THEN CAST (arc_id AS INTEGER)  ELSE 0 END  as feature_id, ''ARC'' as type, arccat_id as featurecat, expl_id FROM v_prefix_arc UNION 
SELECT CASE WHEN node_id~E''^\\d+$'' THEN CAST (node_id AS INTEGER) ELSE 0 END as feature_id, ''NODE'' as type, nodecat_id as featurecat, expl_id FROM v_prefix_node UNION 
SELECT CASE WHEN connec_id~E''^\\d+$'' THEN CAST (connec_id AS INTEGER) ELSE 0 END as feature_id, ''CONNEC'' as type, connecat_id as featurecat, expl_id FROM v_prefix_connec', info_msg='All features with id integer.', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=202;

UPDATE sys_fprocess SET fprocess_name='Connec chain with different arc_id ', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=2, except_msg='chained connecs or gullies with different arc_id. chained connecs with different arc_id.', except_msg_feature=NULL, query_text='with c as 
(select v_prefix_connec.connec_id as id, arc_id as arc, 
v_prefix_connec.connecat_id as feature_catalog, the_geom, v_prefix_connec.expl_id from v_prefix_connec)     
select c1.id, c1.feature_catalog, c1.the_geom, c1.expl_id from link a 
left join c c1 on a.feature_id = c1.id 
left join c c2 on a.exit_id = c2.id 
where (a.exit_type =''CONNEC'') and c1.arc <> c2.arc ', info_msg='All chained connecs and gullies have the same arc_id All chained connecs have the same arc_id', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=205;
UPDATE sys_fprocess SET fprocess_name='Nodes ischange without change of dn/pn/material', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check graph-data', addparam=NULL, except_level=2, except_msg='nodes with ischange on 1 (true) without any variation of arcs in terms of diameter, pn or material. Please, check your data before continue.', except_msg_feature=NULL, query_text='SELECT n.node_id, count(*), nodecat_id, the_geom, a.expl_id FROM (SELECT node_1 as node_id, arccat_id, v_edit_arc.expl_id FROM v_edit_arc WHERE node_1 IN (SELECT node_id FROM v_edit_node JOIN cat_node ON id=nodecat_id WHERE ischange=1) UNION SELECT node_2, arccat_id, v_edit_arc.expl_id FROM v_edit_arc WHERE node_2 IN (SELECT node_id FROM v_edit_node JOIN cat_node ON id=nodecat_id WHERE ischange=1) GROUP BY 1,2,3) a	JOIN node n USING (node_id) GROUP BY 1,3,4,5 HAVING count(*) <> 2', info_msg='No nodes ''ischange'' without real change have been found.', function_name='[gw_fct_graphanalytics_check_data, gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=208;
UPDATE sys_fprocess SET fprocess_name='Change of dn/pn/material without node ischange', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check graph-data', addparam=NULL, except_level=2, except_msg='nodes where arc catalog changes without nodecat with ischange on 0 or 2 (false or maybe). Please, check your data before continue.', except_msg_feature=NULL, query_text='SELECT node_id, nodecat_id, array_agg(arccat_id) as arccat_id, the_geom, node.expl_id FROM ( SELECT count(*), node_id, arccat_id FROM   (SELECT node_1 as node_id, arccat_id FROM v_prefix_arc UNION ALL SELECT node_2, arccat_id FROM v_prefix_arc)a GROUP BY 2,3 HAVING count(*) <> 2 ORDER BY 2) b   JOIN node USING (node_id) JOIN cat_node ON id=nodecat_id WHERE ischange=0 GROUP By 1,2,4,5 HAVING count(*)=2', info_msg='No nodes without ''ischange'' where arc changes have been found', function_name='[gw_fct_graphanalytics_check_data, gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=209;
UPDATE sys_fprocess SET fprocess_name='Mincut results', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=216;
UPDATE sys_fprocess SET fprocess_name='Go2epa-temporal nodarcs', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-network', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=224;
UPDATE sys_fprocess SET fprocess_name='Go2epa check demands data', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=226;
UPDATE sys_fprocess SET fprocess_name='Go2epa check orphan nodes', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-network', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=228;
UPDATE sys_fprocess SET fprocess_name='Go2epa check dry arcs', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-result', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=232;
UPDATE sys_fprocess SET fprocess_name='Go2epa check dry nodes with positive demand', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-network', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=233;
UPDATE sys_fprocess SET fprocess_name='Config mapzones', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=249;
UPDATE sys_fprocess SET fprocess_name='Features state=2 are involved in psector', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check plan-config', addparam=NULL, except_level=3, except_msg='planified arcs without psector. planified nodes without psector. planified connecs without psector. planified gullys without psector. features with state=2 without psector assigned. Please, check your data before continue', except_msg_feature=NULL, query_text='SELECT a.feature_id, a.feature, a.catalog, a.the_geom, count(*) FROM (
SELECT node_id as feature_id, ''NODE'' as feature, nodecat_id as catalog, 
the_geom FROM v_edit_node WHERE state=2 AND node_id NOT IN 
(select node_id FROM plan_psector_x_node) UNION 
SELECT arc_id as feature_id, ''ARC'' as feature, arccat_id as catalog, the_geom  
FROM v_edit_arc WHERE state=2 AND arc_id NOT IN 
(select arc_id FROM plan_psector_x_arc) UNION 
SELECT connec_id as feature_id, ''CONNEC'' as feature, connecat_id  as catalog, 
the_geom  FROM v_edit_connec WHERE state=2 AND connec_id NOT IN 
(select connec_id FROM plan_psector_x_connec)) a  
GROUP BY a.feature_id, a.feature , a.catalog, a.the_geom', info_msg='There are no features with state=2 without psector.', function_name='[gw_fct_plan_check_data, gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=252;
UPDATE sys_fprocess SET fprocess_name='State not according with state_type', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=3, except_msg='features with state without concordance with state_type. Please, check your data before continue features with state without concordance with state_type. Please, check your data before continue', except_msg_feature=NULL, query_text='SELECT arc_id as id, a.state, state_type FROM v_prefix_arc a 
JOIN value_state_type b ON id=state_type WHERE a.state <> b.state UNION 
SELECT node_id as id, a.state, state_type FROM v_prefix_node a 
JOIN value_state_type b ON id=state_type WHERE a.state <> b.state UNION 
SELECT connec_id as id, a.state, state_type FROM v_prefix_connec a 
JOIN value_state_type b ON id=state_type WHERE a.state <> b.state UNION 
SELECT element_id as id, a.state, state_type FROM v_prefix_element a 
JOIN value_state_type b ON id=state_type WHERE a.state <> b.state', info_msg='No features without concordance against state and state_type.   No features without concordance against state and state_type.', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=253;
UPDATE sys_fprocess SET fprocess_name='Features with code null', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=3, except_msg='features with code with NULL values. Please, check your data before continue with code with NULL values. Please, check your data before continue', except_msg_feature=NULL, query_text='SELECT arc_id, arccat_id, the_geom FROM v_prefix_arc WHERE code IS NULL UNION 
SELECT node_id, nodecat_id, the_geom FROM v_prefix_node WHERE code IS NULL UNION 
SELECT connec_id, connecat_id, the_geom FROM v_prefix_connec WHERE code IS NULL UNION 
SELECT element_id, elementcat_id, the_geom FROM v_prefix_element WHERE code IS NULL', info_msg='No features (arc, node, connec, gully, element) with NULL values on code found. No features (arc, node, connec, element) with NULL values on code found.', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=254;
UPDATE sys_fprocess SET fprocess_name='Connec or gully without or with wrong arc_id', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=2, except_msg='connecs without or with incorrect arc_id. gullies without or with incorrect arc_id.', except_msg_feature=NULL, query_text='SELECT c.connec_id, c.connecat_id, c.the_geom, c.expl_id, l.feature_type, link_id FROM arc a, link l 
JOIN connec c ON l.feature_id = c.connec_id WHERE st_dwithin(a.the_geom, st_endpoint(l.the_geom), 0.01) AND exit_type = ''ARC'' 
AND (a.arc_id <> c.arc_id or c.arc_id is null)   AND l.feature_type = ''CONNEC'' AND a.state=1 and c.state = 1 and l.state=1 EXCEPT 
SELECT c.connec_id, c.connecat_id, c.the_geom, c.expl_id, l.feature_type, link_id  FROM node n, link l JOIN connec c ON l.feature_id = c.connec_id 
WHERE st_dwithin(n.the_geom, st_endpoint(l.the_geom), 0.01) AND exit_type IN (''NODE'', ''ARC'')  AND l.feature_type = ''CONNEC'' AND n.state=1 and c.state = 1 
and l.state=1 ORDER BY feature_type, link_id', info_msg='All connecs have correct arc_id. All gullies have correct arc_id.', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=257;
UPDATE sys_fprocess SET fprocess_name='Features state=1 and end date', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=2, except_msg='features on service with value of end date.', except_msg_feature=NULL, query_text='SELECT arc_id as feature_id  from v_prefix_arc where state = 1 and enddate is not null UNION 
SELECT node_id from v_prefix_node where state = 1 and enddate is not null UNION 
SELECT connec_id from v_prefix_connec where state = 1 and enddate is not null', info_msg='No features on service have value of end date', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=262;
UPDATE sys_fprocess SET fprocess_name='Features state=0 without end date', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=2, except_msg='features with state 0 without value of end date.', except_msg_feature=NULL, query_text='SELECT arc_id as feature_id  from v_prefix_arc where state = 0 and enddate is null UNION 
SELECT node_id from v_prefix_node where state = 0 and enddate is null UNION 
SELECT connec_id from v_prefix_connec where state = 0 and enddate is null ', info_msg='No features with state 0 are missing the end date', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=263;
UPDATE sys_fprocess SET fprocess_name='Features state=1 and end date before start date', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=2, except_msg='features with end date earlier than built date.', except_msg_feature=NULL, query_text='SELECT arc_id as feature_id  from v_prefix_arc where enddate < builtdate and state = 1 UNION 
SELECT node_id from v_prefix_node where enddate < builtdate and state = 1 UNION 
SELECT connec_id from v_prefix_connec where enddate < builtdate and state = 1', info_msg='No features with end date earlier than built date', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=264;
UPDATE sys_fprocess SET fprocess_name='Duplicated ID between arc, node, connec, gully', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=3, except_msg='features with duplicated ID value between arc, node, connec, gully features with duplicated ID values between arc, node, connec, gully', except_msg_feature=NULL, query_text='SELECT node_id AS feature_id FROM v_prefix_node n JOIN v_prefix_arc a ON a.arc_id=n.node_id UNION
SELECT node_id FROM v_prefix_node n JOIN v_prefix_connec c ON c.connec_id=n.node_id UNION 
SELECT a.arc_id FROM v_prefix_arc a JOIN v_prefix_connec c ON c.connec_id=a.arc_id', info_msg='All features have a diferent ID to be correctly identified', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=266;
UPDATE sys_fprocess SET fprocess_name='Cat_feature_node without graphdelimiter definition', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check graph-config', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=267;
UPDATE sys_fprocess SET fprocess_name='Sectors without graphconfig', project_type='ws', parameters='{"graphClass":"SECTOR"}'::json, "source"='core', isaudit=true, fprocess_type='Check graph-config', addparam=NULL, except_level=3, except_msg='sectors on sector table with graphconfig not configured.', except_msg_feature=NULL, query_text='SELECT * FROM v_edit_sector WHERE graphconfig IS NULL and sector_id > 0 AND active IS TRUE', info_msg='All sectors has graphconfig values not null.', function_name='[gw_fct_graphanalytics_check_data, gw_fct_admin_check_data]' WHERE fid=268;
UPDATE sys_fprocess SET fprocess_name='DMA without graphconfig', project_type='ws', parameters='{"graphClass":"DMA"}'::json, "source"='core', isaudit=true, fprocess_type='Check graph-config', addparam=NULL, except_level=3, except_msg='dmas on dma table with graphconfig not configured.', except_msg_feature=NULL, query_text='SELECT * FROM v_edit_dma WHERE graphconfig IS NULL and dma_id > 0  AND active IS TRUE', info_msg='All dma has graphconfig values not null.', function_name='[gw_fct_graphanalytics_check_data, gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=269;
UPDATE sys_fprocess SET fprocess_name='DQA without graphconfig', project_type='ws', parameters='{"graphClass":"DQA"}'::json, "source"='core', isaudit=true, fprocess_type='Check graph-config', addparam=NULL, except_level=3, except_msg='dqas on dqa table with graphconfig not configured.', except_msg_feature=NULL, query_text='SELECT * FROM v_edit_dqa WHERE graphconfig IS NULL and dqa_id > 0 AND active IS TRUE', info_msg='All dqa has graphconfig values not null.', function_name='[gw_fct_graphanalytics_check_data, gw_fct_admin_check_data]' WHERE fid=270;
UPDATE sys_fprocess SET fprocess_name='Presszone without graphconfig', project_type='ws', parameters='{"graphClass":"PRESSZONE"}'::json, "source"='core', isaudit=true, fprocess_type='Check graph-config', addparam=NULL, except_level=3, except_msg='presszones on presszone table with graphconfig not configured.', except_msg_feature=NULL, query_text='SELECT * FROM v_edit_presszone WHERE graphconfig IS NULL and presszone_id > 0::text AND active IS TRUE', info_msg='All presszones has graphconfig values not null.', function_name='[gw_fct_graphanalytics_check_data, gw_fct_admin_check_data]' WHERE fid=271;
UPDATE sys_fprocess SET fprocess_name='Null values on valv_type table', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=3, except_msg='valves with null values on valv_type column.', except_msg_feature=NULL, query_text='SELECT * FROM v_edit_inp_valve WHERE valv_type IS NULL', info_msg='Valve valv_type checked. No mandatory values missed.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=273;
UPDATE sys_fprocess SET fprocess_name='Null values on valve status', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=3, except_msg='valves with null values on mandatory column status.', except_msg_feature=NULL, query_text='SELECT * FROM v_edit_inp_valve WHERE status IS NULL AND state > 0', info_msg='Valve status checked. No mandatory values missed.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=274;
UPDATE sys_fprocess SET fprocess_name='Null values on valve pressure', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=3, except_msg='PBV-PRV-PSV valves with null values on the mandatory column for Pressure valves.', except_msg_feature=NULL, query_text='SELECT * FROM v_edit_inp_valve WHERE ((valv_type=''PBV'' OR valv_type=''PRV'' OR valv_type=''PSV'') AND (pressure IS NULL))', info_msg='PBC-PRV-PSV valves checked. No mandatory values missed.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=275;
UPDATE sys_fprocess SET fprocess_name='Null values on GPV valve config', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=3, except_msg='GPV valves with null values on mandatory column for General purpose valves.', except_msg_feature=NULL, query_text='SELECT * FROM v_edit_inp_valve WHERE ((valv_type=''GPV'') AND (curve_id IS NULL))', info_msg='GPV valves checked. No mandatory values missed.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=276;
UPDATE sys_fprocess SET fprocess_name='Null values on TCV valve config', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=3, except_msg='TCV valves with null values on mandatory column for Losses Valves.', except_msg_feature=NULL, query_text='SELECT * FROM v_edit_inp_valve WHERE valv_type=''TCV'' AND coef_loss IS NULL', info_msg='TCV valves checked. No mandatory values missed.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=277;
UPDATE sys_fprocess SET fprocess_name='Null values on FCV valve config', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=3, except_msg='FCV valves with null values on mandatory column for Flow Control Valves.', except_msg_feature=NULL, query_text='SELECT * FROM v_edit_inp_valve WHERE ((valv_type=''FCV'') AND (flow IS NULL))', info_msg='FCV valves checked. No mandatory values missed.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=278;
UPDATE sys_fprocess SET fprocess_name='Null values on pump type', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=3, except_msg='pumps with null values on pump_type column. virtualpump''''s with null values on pump_type column.', except_msg_feature=NULL, query_text='SELECT * FROM v_edit_inp_pump WHERE pump_type IS NULL', info_msg='Pumps checked. No mandatory values for pump_type missed.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=279;
UPDATE sys_fprocess SET fprocess_name='Null values on pump curve_id ', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=3, except_msg='pumps with null values at least on mandatory column curve_id. virtualpumps with null values at least on mandatory column curve_id.', except_msg_feature=NULL, query_text='SELECT * FROM v_edit_inp_pump WHERE curve_id IS NULL', info_msg='Pumps checked. No mandatory values for curve_id missed. Virtualpumps checked. No mandatory values for curve_id missed.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=280;
UPDATE sys_fprocess SET fprocess_name='Null values on additional pump curve_id ', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=3, except_msg='additional pumps with null values at least on mandatory column curve_id.', except_msg_feature=NULL, query_text='SELECT * FROM inp_pump_additional JOIN v_edit_inp_pump USING (node_id) WHERE inp_pump_additional.curve_id IS NULL', info_msg='Additional pumps checked. No mandatory values for curve_id missed.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=281;
UPDATE sys_fprocess SET fprocess_name='Null values on roughness catalog ', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-config', addparam=NULL, except_level=3, except_msg='pipes with null values for roughness. Check roughness catalog columns (init_age,end_age,roughness) before continue.''', except_msg_feature=NULL, query_text='SELECT * FROM v_edit_inp_pipe JOIN cat_arc ON id = arccat_id JOIN cat_mat_roughness USING  (matcat_id) WHERE init_age IS NULL OR end_age IS NULL OR roughness IS NULL', info_msg='Roughness catalog checked. No mandatory values missed.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=282;
UPDATE sys_fprocess SET fprocess_name='Null values on arc catalog - dint', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-config', addparam=NULL, except_level=3, except_msg='registers on arc''''s catalog with null values on dint column.''', except_msg_feature=NULL, query_text='SELECT * FROM cat_arc WHERE dint IS NULL', info_msg='Dint for arc''''s catalog checked. No values missed.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=283;
UPDATE sys_fprocess SET fprocess_name='Connec or gully with different expl_id than arc', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=3, except_msg='connecs with exploitation different than the exploitation of the related arc', except_msg_feature=NULL, query_text='SELECT DISTINCT connec_id, connecat_id, c.the_geom, c.expl_id 
FROM v_prefix_connec c JOIN v_prefix_arc b using (arc_id) WHERE b.expl_id::text != c.expl_id::text', info_msg='All connecs or gullys have the same exploitation as the related arc', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=291;
UPDATE sys_fprocess SET fprocess_name='Non-mandatory nodarc with less than two arcs', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-topology', addparam=NULL, except_level=2, except_msg='NON-mandatory node2arcs with less than two arcs. It will be transformed on the fly using only one arc''', except_msg_feature=NULL, query_text='SELECT * FROM temp_anl_node WHERE fid = 292', info_msg='No results found for NON-mandatory node2arcs with less than two arcs.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=292;
UPDATE sys_fprocess SET fprocess_name='Check cat_feature_node field graph_delimiter', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check admin', addparam=NULL, except_level=3, except_msg='nodes without value on field "graph_delimiter" from cat_feature_node.', except_msg_feature=NULL, query_text='SELECT * FROM cat_feature_node WHERE graph_delimiter IS NULL', info_msg='All nodes have value on field "graph_delimiter"', function_name='[gw_fct_admin_check_data]' WHERE fid=307;
UPDATE sys_fprocess SET fprocess_name='Check cat_node field estimated_depth', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check plan-config', addparam=NULL, except_level=2, except_msg='rows without values on cat_node.estimated_depth column.', except_msg_feature=NULL, query_text='SELECT * FROM cat_node WHERE estimated_depth IS NULL and active=TRUE', info_msg='There is/are no rows without values on cat_node.estimated_depth column.', function_name='[gw_fct_plan_check_data, gw_fct_admin_check_data]' WHERE fid=330;
UPDATE sys_fprocess SET fprocess_name='Planned connecs without reference link', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=3, except_msg='planned connecs without reference link planned connecs or gullys without reference link', except_msg_feature=NULL, query_text='SELECT * FROM plan_psector_x_connec WHERE link_id IS NULL ', info_msg='All planned connecs or gullys have a reference link', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=356;
UPDATE sys_fprocess SET fprocess_name='Set configuration of field to_arc', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=359;
UPDATE sys_fprocess SET fprocess_name='Flow values', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=363;
UPDATE sys_fprocess SET fprocess_name='Pressure values', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=364;
UPDATE sys_fprocess SET fprocess_name='Clorinathor values', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=365;
UPDATE sys_fprocess SET fprocess_name='Temperature values', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=366;
UPDATE sys_fprocess SET fprocess_name='Check if defined arcs (toArc) exist in a database', project_type='ws', parameters='{"graphClass":"PRESSZONE"}'::json, "source"='core', isaudit=true, fprocess_type='Check graph-data', addparam=NULL, except_level=2, except_msg='arcs that are configured as toArc for v_prefix_v_graphclass but is not operative on arc table.', except_msg_feature=NULL, query_text='SELECT b.arc_id, b.v_graphclass_id as zone_id FROM ( SELECT v_graphclass_id, json_array_elements_text(((json_array_elements_text((graphconfig::json->>''use'')::json))::json->>''toArc'')::json) as arc_id FROM v_prefix_v_graphclass)b 
WHERE arc_id not in (select arc_id FROM arc WHERE state=1)', info_msg='All arcs defined as toArc on v_prefix_v_graphclass exists on DB.', function_name='[gw_fct_graphanalytics_check_data, gw_fct_admin_check_data]' WHERE fid=367;
UPDATE sys_fprocess SET fprocess_name='Null values on to_arc valves', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=3, except_msg='valves with missed values on mandatory column to_arc.', except_msg_feature=NULL, query_text='SELECT * FROM v_edit_inp_valve WHERE to_arc IS NULL', info_msg='Valve to_arc missed values checked. No mandatory values missed.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=368;
UPDATE sys_fprocess SET fprocess_name='Check arc catalog with matcat_id null', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-config', addparam=NULL, except_level=3, except_msg='rows with missed matcat_id on cat_arc table. Fix it before continue''', except_msg_feature=NULL, query_text='SELECT * FROM cat_arc WHERE matcat_id IS NULL', info_msg='No registers found without material on cat_arc table.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=371;
UPDATE sys_fprocess SET fprocess_name='Check period configuration for dma', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=374;
UPDATE sys_fprocess SET fprocess_name='Check roughness configuration', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-result', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=377;
UPDATE sys_fprocess SET fprocess_name='Check hydrometer configuration', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Not used', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=378;
UPDATE sys_fprocess SET fprocess_name='Check to_arc missed VALUES for pumps', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-data', addparam=NULL, except_level=3, except_msg='pumps with missed values on mandatory column to_arc.', except_msg_feature=NULL, query_text='SELECT * FROM v_edit_inp_pump WHERE to_arc IS NULL', info_msg='Pump to_arc missed values checked. No mandatory values missed.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=395;
UPDATE sys_fprocess SET fprocess_name='Null values on dint for registres on cat_connec)', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-result', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=400;
UPDATE sys_fprocess SET fprocess_name='Builddate before 1900', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=2, except_msg='features with built date before 1900.', except_msg_feature=NULL, query_text='SELECT arc_id, ''ARC''::text FROM v_prefix_arc WHERE builtdate < ''1900/01/01''::date UNION 
SELECT  node_id, ''NODE''::text FROM v_prefix_node WHERE builtdate < ''1900/01/01''::date UNION 
SELECT  connec_id, ''CONNEC''::text FROM v_prefix_connec WHERE builtdate < ''1900/01/01''::date', info_msg='No feature with builtdate before 1900.', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=406;
UPDATE sys_fprocess SET fprocess_name='Create dscenario from ToC', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=410;
UPDATE sys_fprocess SET fprocess_name='Mandatory nodarc over other EPA node', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-topology', addparam=NULL, except_level=3, except_msg='mandatory nodarcs (VALVE & PUMP) over other EPA nodes.'' ', except_msg_feature=NULL, query_text='SELECT a.* FROM (SELECT DISTINCT t1.node_id as n1, t1.nodecat_id as n1cat, t1.state as state1, t2.node_id as n2, 
t2.nodecat_id as n2cat, t2.state as state2, t1.expl_id, 411, 
t1.the_geom, st_distance(t1.the_geom, t2.the_geom) as dist, t1.sector_id  
FROM node AS t1 JOIN node AS t2 ON ST_Dwithin(t1.the_geom, t2.the_geom, 0.01) 
WHERE t1.node_id != t2.node_id AND ((t1.epa_type IN (''PUMP'', ''VALVE'') AND t2.epa_type !=''UNDEFINED'') OR 
(t2.epa_type IN (''PUMP'', ''VALVE'') AND t1.epa_type !=''UNDEFINED''))  ORDER BY t1.node_id) a, selector_expl e, selector_sector s  
WHERE e.expl_id = a.expl_id AND e.cur_user = current_user   AND s.sector_id = a.sector_id 
AND s.cur_user = current_user  AND a.state1 > 0 AND a.state2 > 0 ORDER BY dist', info_msg=' All mandatory nodarc (PUMP & VALVE) are not on the same position than other EPA nodes.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=411;
UPDATE sys_fprocess SET fprocess_name='Shortpipe nodarc over other EPA node', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-topology', addparam=NULL, except_level=2, except_msg='shortpipe nodarcs over other EPA nodes.''', except_msg_feature=NULL, query_text='SELECT * FROM (  SELECT DISTINCT t1.node_id as n1, t1.nodecat_id as n1cat, t1.state as state1, t2.node_id as n2, t2.nodecat_id as n2cat, t2.state as state2, t1.expl_id, 412,   t1.the_geom, st_distance(t1.the_geom, t2.the_geom) as dist, ''Shortpipe nodarc over other EPA node'' as descript  FROM selector_expl e, selector_sector s, node AS t1 JOIN node AS t2 ON ST_Dwithin(t1.the_geom, t2.the_geom, 0.01)   WHERE t1.node_id != t2.node_id   AND s.sector_id = t1.sector_id AND s.cur_user = current_user  AND e.expl_id = t1.expl_id AND e.cur_user = current_user   AND ((t1.epa_type = ''SHORTPIPE'' AND t2.epa_type =''JUNCTION'') OR (t2.epa_type = ''SHORTPIPE'' AND t1.epa_type !=''JUNCTION''))  AND t1.node_id =''SHORTPIPE''  ORDER BY t1.node_id) a where a.state1 > 0 AND a.state2 > 0 ORDER BY dist', info_msg='All shortpipe nodarcs are not on the same position than other EPA nodes.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=412;
UPDATE sys_fprocess SET fprocess_name='EPA connec over EPA node', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-result', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=413;
UPDATE sys_fprocess SET fprocess_name='Cat connec rows without dint', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-result', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=414;
UPDATE sys_fprocess SET fprocess_name='Check category_type values exists on man_ table', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=3, except_msg='features with category_type does not exists on man_type_category table.', except_msg_feature=NULL, query_text='SELECT ''ARC'', arc_id, category_type FROM v_prefix_arc WHERE category_type NOT IN (SELECT category_type FROM man_type_category WHERE feature_type is null or feature_type = ''ARC'' or featurecat_id IS NOT NULL) AND category_type IS NOT NULL
UNION
SELECT ''NODE'', node_id, category_type FROM v_prefix_node WHERE category_type NOT IN (SELECT category_type FROM man_type_category WHERE feature_type is null or feature_type = ''NODE'' or featurecat_id IS NOT NULL) AND category_type IS NOT NULL
UNION
SELECT ''CONNEC'', connec_id, category_type FROM v_prefix_connec WHERE category_type NOT IN (SELECT category_type FROM man_type_category WHERE feature_type is null or feature_type = ''CONNEC'' or featurecat_id IS NOT NULL) AND category_type IS NOT NULL', info_msg='All features has category_type informed on man_type_category table', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=421;
UPDATE sys_fprocess SET fprocess_name='Check function_type values exists on man_ table', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=3, except_msg='features with function_type does not exists on man_type_function table.', except_msg_feature=NULL, query_text='SELECT ''ARC'', arc_id, function_type FROM v_prefix_arc WHERE function_type NOT IN (SELECT function_type FROM man_type_function WHERE feature_type is null or feature_type = ''ARC'' or featurecat_id IS NOT NULL) AND function_type IS NOT NULL
UNION
SELECT ''NODE'', node_id, function_type FROM v_prefix_node WHERE function_type NOT IN (SELECT function_type FROM man_type_function WHERE feature_type is null or feature_type = ''NODE'' or featurecat_id IS NOT NULL) AND function_type IS NOT NULL
UNION
SELECT ''CONNEC'', connec_id, function_type FROM v_prefix_connec WHERE function_type NOT IN (SELECT function_type FROM man_type_function WHERE feature_type is null or feature_type = ''CONNEC'' or featurecat_id IS NOT NULL) AND function_type IS NOT NULL', info_msg='All features has function_type informed on man_type_function table', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=422;
UPDATE sys_fprocess SET fprocess_name='Check fluid_type values exists on man_ table', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=3, except_msg='features with fluid_type does not exists on man_type_fluid table.', except_msg_feature=NULL, query_text='SELECT ''ARC'', arc_id, fluid_type FROM v_prefix_arc WHERE fluid_type NOT IN (SELECT fluid_type FROM man_type_fluid WHERE feature_type is null or feature_type = ''ARC'' or featurecat_id IS NOT NULL) AND fluid_type IS NOT NULL
UNION
SELECT ''NODE'', node_id, fluid_type FROM v_prefix_node WHERE fluid_type NOT IN (SELECT fluid_type FROM man_type_fluid WHERE feature_type is null or feature_type = ''NODE'' or featurecat_id IS NOT NULL) AND fluid_type IS NOT NULL
UNION
SELECT ''CONNEC'', connec_id, fluid_type FROM v_prefix_connec WHERE fluid_type NOT IN (SELECT fluid_type FROM man_type_fluid WHERE feature_type is null or feature_type = ''CONNEC'' or featurecat_id IS NOT NULL) AND fluid_type IS NOT NULL', info_msg='All features has fluid_type informed on man_type_fluid table', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=423;
UPDATE sys_fprocess SET fprocess_name='Check location_type values exists on man_ table', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=3, except_msg='features with location_type does not exists on man_type_location table.', except_msg_feature=NULL, query_text='SELECT ''ARC'', arc_id, location_type FROM v_prefix_arc WHERE location_type NOT IN (SELECT location_type FROM man_type_location WHERE feature_type is null or feature_type = ''ARC'' or featurecat_id IS NOT NULL) AND location_type IS NOT NULL
UNION
SELECT ''NODE'', node_id, location_type FROM v_prefix_node WHERE location_type NOT IN (SELECT location_type FROM man_type_location WHERE feature_type is null or feature_type = ''NODE'' or featurecat_id IS NOT NULL) AND location_type IS NOT NULL
UNION
SELECT ''CONNEC'', connec_id, location_type FROM v_prefix_connec WHERE location_type NOT IN (SELECT location_type FROM man_type_location WHERE feature_type is null or feature_type = ''CONNEC'' or featurecat_id IS NOT NULL) AND location_type IS NOT NULL', info_msg='All features has location_type informed on man_type_location table', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=424;
UPDATE sys_fprocess SET fprocess_name='Check minlength less than 0.01 or more than node proximity', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-topology', addparam=NULL, except_level=3, except_msg='minlength value is bad configured (more than node proximity or less than 0.01).', except_msg_feature=NULL, query_text='WITH subq_1 AS (
SELECT value::numeric as v_minlength FROM config_param_system WHERE parameter = ''epa_arc_minlength''
), subq_2 as (
SELECT (value::json->>''value'')::numeric as v_nodeproximity FROM config_param_system WHERE parameter = ''edit_node_proximity''
), mec as (
select v_minlength < 0.01 or v_minlength >= v_nodeproximity as results from subq_1, subq_2
) select * from mec where results is true', info_msg='Minlength value ('',v_minlength,'') is well configured.''', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=425;
UPDATE sys_fprocess SET fprocess_name='Arc materials not defined in cat_mat_roughness table', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check epa-config', addparam=NULL, except_level=3, except_msg='arc materials that are not defined in cat_mat_rougnhess table. Please, check your data before continue.''', except_msg_feature=NULL, query_text='SELECT id FROM cat_mat_arc WHERE id NOT IN (SELECT matcat_id FROM cat_mat_roughness)', info_msg='All arc materials are defined on cat_mat_rougnhess table.', function_name='[gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=433;
UPDATE sys_fprocess SET fprocess_name='Water balance calculation', project_type='ws', parameters=NULL, "source"='core', isaudit=false, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=441;
UPDATE sys_fprocess SET fprocess_name='Node orphan with isarcdivide=TRUE (OM)', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-topology', addparam=NULL, except_level=2, except_msg='orphan nodes with isarcdivide=TRUE.', except_msg_feature=NULL, query_text='SELECT * FROM v_prefix_node a JOIN cat_node nc ON nodecat_id=id JOIN cat_feature_node nt ON nt.id=nc.nodetype_id WHERE a.state>0 AND isarcdivide = true
	AND (SELECT COUNT(*) FROM arc WHERE node_1 = a.node_id OR node_2 = a.node_id and arc.state>0) = 0', info_msg='There are no orphan nodes with isarcdivide=TRUE', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=442;
UPDATE sys_fprocess SET fprocess_name='Node orphan with isarcdivide=FALSE (OM)', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-topology', addparam=NULL, except_level=2, except_msg='orphan nodes with isarcdivide=FALSE.', except_msg_feature=NULL, query_text='SELECT  * FROM node a JOIN cat_node nc ON nodecat_id=id JOIN cat_feature_node nt ON nt.id=nc.nodetype_id WHERE a.state>0 AND isarcdivide=false AND arc_id IS NULL', info_msg='There are no orphan nodes with isarcdivide=FALSE', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=443;
UPDATE sys_fprocess SET fprocess_name='Check zones without numeric id', project_type='ws', parameters='{"graphClass":"PRESSZONE"}'::json, "source"='core', isaudit=true, fprocess_type='Check graph-data', addparam=NULL, except_level=3, except_msg='presszones with id that is not a numeric value.', except_msg_feature=NULL, query_text='SELECT presszone_id FROM presszone WHERE presszone_id=''-1'' AND presszone_id ~''^\d+(\.\d+)?$'' is false', info_msg='All presszone_ids are numeric values.', function_name='[gw_fct_graphanalytics_check_data, gw_fct_admin_check_data]' WHERE fid=460;
UPDATE sys_fprocess SET fprocess_name='Planified EPANET pumps with more than two acs', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check plan-data', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=462;
UPDATE sys_fprocess SET fprocess_name='Graph analysis for hydrants', project_type='ws', parameters=NULL, "source"='core', isaudit=false, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=463;
UPDATE sys_fprocess SET fprocess_name='Graph analysis for hydrants - marking crossroads', project_type='ws', parameters=NULL, "source"='core', isaudit=false, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=464;
UPDATE sys_fprocess SET fprocess_name='Planified EPANET pumps with more than two acs', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check plan-data', addparam=NULL, except_level=3, except_msg='pumpss with more than two arcs .Take a look on temporal table to details', except_msg_feature=NULL, query_text='SELECT * FROM temp_anl_node WHERE fid=467 AND cur_user=current_user', info_msg='EPA pumps checked. No pumps with more than two arcs detected.', function_name='[gw_fct_plan_check_data, gw_fct_admin_check_data]' WHERE fid=467;
UPDATE sys_fprocess SET fprocess_name='Graph analysis for hydrants - hydrant proposal', project_type='ws', parameters=NULL, "source"='core', isaudit=false, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=468;
UPDATE sys_fprocess SET fprocess_name='Get epa calibration file for pressures', project_type='ws', parameters=NULL, "source"='GW Epa Tools', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=474;
UPDATE sys_fprocess SET fprocess_name='Get epa calibration file for volumes', project_type='ws', parameters=NULL, "source"='GW Epa Tools', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=475;
UPDATE sys_fprocess SET fprocess_name='Get log for epa calibration volumes', project_type='ws', parameters=NULL, "source"='GW Epa Tools', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=476;
UPDATE sys_fprocess SET fprocess_name='Check features without defined sector_id', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=2, except_msg='connecs with sector_id 0 or -1.', except_msg_feature=NULL, query_text='SELECT connec_id, connecat_id, the_geom, expl_id FROM connec WHERE state > 0 
AND (sector_id=0 OR sector_id=-1)', info_msg='No connecs with 0 or -1 value on sector_id.', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=478;
UPDATE sys_fprocess SET fprocess_name='Check connecs with more than 1 link on service', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=2, except_msg='connecs with more than 1 link on service', except_msg_feature=NULL, query_text='SELECT connec_id, connecat_id, the_geom, expl_id FROM connec WHERE connec_id IN 
(SELECT feature_id FROM link WHERE state=1 GROUP BY feature_id HAVING count(*) > 1)', info_msg='No connects with more than 1 link on service', function_name='[gw_fct_om_check_data, gw_fct_pg2epa_check_data, gw_fct_admin_check_data]' WHERE fid=480;
UPDATE sys_fprocess SET fprocess_name='Check connecs related to arcs with diameter bigger than defined value', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Check om-data', addparam=NULL, except_level=2, except_msg='connecs related to arcs with diameter bigger than defined value.', except_msg_feature=NULL, query_text='WITH subq_1 AS (
SELECT (value::json->>''status'')::boolean as status FROM config_param_system WHERE parameter = ''edit_link_check_arcdnom''
), subq_2 as (
select (value::json->>''diameter'')::numeric as v_check_arcdnom FROM config_param_system, subq_1 
WHERE parameter = ''edit_link_check_arcdnom'' and status is true)
SELECT connec_id, connecat_id, the_geom, expl_id 
FROM v_prefix_connec, subq_2 WHERE state>0 AND arc_id IN 
(SELECT arc_id FROM v_prefix_arc JOIN cat_arc ON arccat_id=id WHERE dnom::integer>subq_2.v_check_arcdnom)', info_msg='No connecs related to arcs with diameter bigger than defined value', function_name='[gw_fct_om_check_data]' WHERE fid=488;
UPDATE sys_fprocess SET fprocess_name='Show current mincuts', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=490;
UPDATE sys_fprocess SET fprocess_name='Check demands export input file', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=491;
UPDATE sys_fprocess SET fprocess_name='Check demands import results', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=492;
UPDATE sys_fprocess SET fprocess_name='Check valve status export input file', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=493;
UPDATE sys_fprocess SET fprocess_name='Check valve status demands import results', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=494;
UPDATE sys_fprocess SET fprocess_name='Check orphan documents', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=2, except_msg='documents not related to any feature.', except_msg_feature=NULL, query_text='select id from doc where id not in 
(select distinct  doc_id from doc_x_arc UNION 
select distinct  doc_id from doc_x_connec UNION 
select distinct  doc_id from doc_x_node)', info_msg='All documents are related to the features.', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=497;
UPDATE sys_fprocess SET fprocess_name='Check orphan visits', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=2, except_msg='visits not related to any feature and without geometry.', except_msg_feature=NULL, query_text='select id, the_geom from om_visit where the_geom is null and id not in 
(select distinct visit_id from om_visit_x_arc UNION 
select distinct visit_id from om_visit_x_connec UNION 
select distinct visit_id from om_visit_x_node)', info_msg='All visits are related to the features or have geometry.', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=498;
UPDATE sys_fprocess SET fprocess_name='Check orphan elements', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=2, except_msg='elements not related to any feature and without geometry.', except_msg_feature=NULL, query_text='select element_id, the_geom from element where the_geom is null and element_id not in (select distinct element_id from element_x_arc UNION 
select distinct element_id from element_x_connec UNION 
select distinct element_id from element_x_node)', info_msg='All elements are related to the features or have geometry.', function_name='[gw_fct_om_check_data, gw_fct_admin_check_data]' WHERE fid=499;
UPDATE sys_fprocess SET fprocess_name='Import valve status', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=500;
UPDATE sys_fprocess SET fprocess_name='Import dscenario demands', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=501;
UPDATE sys_fprocess SET fprocess_name='Set dscenario demand using netscenario', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=502;
UPDATE sys_fprocess SET fprocess_name='Import flowmeter daily values', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=504;
UPDATE sys_fprocess SET fprocess_name='Import flowmeter agg values', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=506;
UPDATE sys_fprocess SET fprocess_name='Create new Netscenario', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=508;
UPDATE sys_fprocess SET fprocess_name='Duplicate Netscenario', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=510;
UPDATE sys_fprocess SET fprocess_name='Import valve closed into netscenario', project_type='ws', parameters=NULL, "source"='core', isaudit=true, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=514;
UPDATE sys_fprocess SET fprocess_name='fprocess to set cost for removed material on psectors', project_type='ws', parameters=NULL, "source"='core', isaudit=false, fprocess_type='Function process', addparam=NULL, except_level=NULL, except_msg=NULL, except_msg_feature=NULL, query_text=NULL, info_msg=NULL, function_name=NULL WHERE fid=523;