name: CI Test UD database

on:
  push:
    branches: [dev-3.6]
  pull_request:
    branches: [dev-3.6]

jobs:
  ci_test_ud_db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test/requirements.txt

      - name: Add PostgreSQL repository
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

      - name: Update apt-get and Install PostgreSQL, PostGIS, pgRouting, and pgTAP
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-15 postgresql-15-postgis-3 postgresql-15-pgrouting postgresql-15-pgtap postgis

      - name: Start PostgreSQL service
        run: |
          sudo service postgresql start
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"

      - name: Create PostgreSQL Database
        env:
          PGPASSWORD: postgres
        run: |
          psql -h localhost -U postgres -c 'CREATE DATABASE gw_db;'

      - name: Setup PostgreSQL extensions
        env:
          PGPASSWORD: postgres
        run: |
          psql -h localhost -U postgres -d gw_db -c 'CREATE EXTENSION postgis;'
          psql -h localhost -U postgres -d gw_db -c 'CREATE EXTENSION pgrouting;'
          psql -h localhost -U postgres -d gw_db -c 'CREATE EXTENSION postgis_raster;'
          psql -h localhost -U postgres -d gw_db -c 'CREATE EXTENSION postgis_topology;'
          psql -h localhost -U postgres -d gw_db -c 'CREATE EXTENSION pgtap;'

      - name: Replace variables in SQL files
        run: python test/replace_vars.py ud

      - name: Create Sample Schema
        env:
          PGPASSWORD: postgres
        run: python test/execute_sql_files.py ud

      - name: Run SQL Tests with pgTAP and pg_prove (PL/SQL)
        env:
          PGPASSWORD: postgres
        run: |
          pg_prove -h localhost -U postgres -d gw_db test/plsql/ud/*.sql

      - name: Run SQL Tests with pgTAP and pg_prove (UPSERT)
        env:
          PGPASSWORD: postgres
        run: |
          pg_prove -h localhost -U postgres -d gw_db test/upsert/ud/*.sql

      - name: Run SQL Tests with pgTAP and pg_prove (STRUCTURE)
        env:
          PGPASSWORD: postgres
        run: |
          pg_prove -h localhost -U postgres -d gw_db test/structure/ud/*.sql
